format:
    name: instr_none_QA
    prefix_seed: 0
    header: ""
    L1_delim: 
        value: "Q:"
        type: "string"
        n_toks: 1
    L2_delim: 
        value: "\nA:"
        type: "string"
        init: string
        n_toks: 1
    eos: ""
    sep: "\n"
    delim: prefix 
    sep_init: lang
    prefix_configs: ""
    weight_configs: ""
    join_tasks: raw
