format:
    name: instr_machine_translation
    prefix_seed: 0
    header: "Translate <L1> to <L2>:" 
    L1_delim: 
        value: "Q:"
        type: "string"
        n_toks: 1
    L2_delim: 
        value: "A:" 
        type: "string"
        init: lang 
        n_toks: 1
    eos: ""
    sep: "\n"
