format:
    name: instr_code_gen
    prefix_seed: 0
    header: "Write a program for the following task:\n"
    L1_delim: 
        value: "Q:"
        type: "string"
        n_toks: 1
    L2_delim: 
        value: "\nA:" # a spaec here is also bad. what's wrong w the tokenization
        type: "string"
        init: lang 
        n_toks: 1
    eos: ""
    sep: "\n"
#    delim: prefix 
#    sep_init: lang
# space after header semi-colon bad?
